### ISSUE TITLE
Add documentation for k8s credentials

### ISSUE THREAD

**Issue by laixer** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#22] opened 2016-10-07 06:13 UTC

**Comment by kurtisvg** [comment] 2019-06-12 21:16
Closing this - shouldn't be anything special for using this connector in a k8s environment. If the issue is regards to secrets management, I think that subject is better left to the k8s docs.

**Closed by kurtisvg** 2019-06-12 21:16 UTC
Labels: Priority: Low, Status: Proposal, Type: Documentation
