### ISSUE TITLE
First connection taking a significant amount of time in J11 GCF

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#237] opened 2020-07-27 21:32 UTC
## Bug Description

Originally described in #236, generating the RSA key pair seems to be taking a considerable amount of time. We should benchmark this and see if there is a way to optimize the performance in this runtime.

May potentially be related to initializing two datasources sequentially. 

## Example code (or command)

```java
// TODO
```

**Comment by shubha-rajan** [comment] 2020-10-14 23:16
After benchmarking this, I was unable to reproduce the slow connection times described in #236. I'll close this for now and reopen if we start to see issues again.

**Closed by shubha-rajan** 2020-10-14 23:16 UTC
Labels: type: bug
