### ISSUE TITLE
r2dbc core: Blocked main thread on createSslCustomizer 

### ISSUE THREAD

**Issue by magiccrafter** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#871] opened 2022-06-08 13:08 UTC
## Bug Description

The current version of the library seems to block the main thread with the latest Netty & R2DBC driver/SPI.

Profiling results:
CPU Utilization:
<img width="1197" alt="profiler_cpu_load" src="https://user-images.githubusercontent.com/1208518/172622114-8801313c-ec15-4ec2-9088-b5ae2c5a68e9.png">
Between the 12th and 14th minutes, I've run a very light load test of 2 rps to troubleshoot the problem faster.  

CPU Thread HotSpots:
<img width="1231" alt="profiling_cpu_thread_hotspots1" src="https://user-images.githubusercontent.com/1208518/172622555-cfe87704-baae-4927-92cc-218b52dc5dd4.png">
<img width="1222" alt="profiling_cpu_thread_hotspots2" src="https://user-images.githubusercontent.com/1208518/172622459-ee2b5a15-160b-485c-86ea-48974173af5e.png">
<img width="1226" alt="profiling_cpu_thread_hotspots3" src="https://user-images.githubusercontent.com/1208518/172622473-90150ce1-049c-45a1-9275-16cf4a88a639.png">

Versions of the libraries used to reproduce the problem:
Spring Boot: 2.7.0
Nety Core: 4.1.77.Final
Reactor netty: 1.0.19
io.r2dbc:r2dbc spi: 0.9.1.RELEASE
io.r2dbc:r2dbc pool: 0.9.0.RELEASE
org.postgresql:r2dbc-postgresql:jar:0.9.1.RELEASE

for more details check the dependency tree:
```
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.7.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-webflux:jar:2.7.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.7.0:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.19:compile
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.1.77.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http2:jar:4.1.77.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.77.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.77.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.77.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.77.Final:compile
[INFO] |  |     \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.77.Final:compile
[INFO] |  \- org.springframework:spring-webflux:jar:5.3.20:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-r2dbc:jar:2.7.0:compile
[INFO] |  +- org.springframework.data:spring-data-r2dbc:jar:1.5.0:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.7.0:compile
[INFO] |  |  +- org.springframework.data:spring-data-relational:jar:2.4.0:compile
[INFO] |  |  \- org.springframework:spring-r2dbc:jar:5.3.20:compile
[INFO] |  +- io.r2dbc:r2dbc-spi:jar:0.9.1.RELEASE:compile
[INFO] |  \- io.r2dbc:r2dbc-pool:jar:0.9.0.RELEASE:compile
[INFO] |     \- io.projectreactor.addons:reactor-pool:jar:0.2.8:compile
[INFO] +- org.postgresql:r2dbc-postgresql:jar:0.9.1.RELEASE:compile
[INFO] |  +- com.ongres.scram:client:jar:2.1:compile
[INFO] |  |  \- com.ongres.scram:common:jar:2.1:compile
[INFO] |  |     \- com.ongres.stringprep:saslprep:jar:1.1:compile
[INFO] |  |        \- com.ongres.stringprep:stringprep:jar:1.1:compile
[INFO] |  \- io.projectreactor.netty:reactor-netty:jar:1.0.19:compile
[INFO] |     +- io.projectreactor.netty:reactor-netty-core:jar:1.0.19:compile
[INFO] |     |  \- io.netty:netty-handler-proxy:jar:4.1.77.Final:compile
[INFO] |     |     \- io.netty:netty-codec-socks:jar:4.1.77.Final:compile
[INFO] |     +- io.projectreactor.netty.incubator:reactor-netty-incubator-quic:jar:0.0.8:runtime
[INFO] |     |  \- io.netty.incubator:netty-incubator-codec-native-quic:jar:linux-x86_64:0.0.26.Final:runtime
[INFO] |     |     \- io.netty.incubator:netty-incubator-codec-classes-quic:jar:0.0.26.Final:runtime
[INFO] |     \- io.projectreactor.netty:reactor-netty-http-brave:jar:1.0.19:runtime
[INFO] |        \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.9:compile
[INFO] +- com.google.cloud.sql:cloud-sql-connector-r2dbc-postgres:jar:1.6.0:compile
[INFO] |  +- com.google.cloud.sql:cloud-sql-connector-r2dbc-core:jar:1.6.0:compile
[INFO] |  +- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.6.0:compile
[INFO] |  |  +- com.github.jnr:jnr-unixsocket:jar:0.38.17:compile
[INFO] |  |  |  +- com.github.jnr:jnr-ffi:jar:2.2.11:compile
[INFO] |  |  |  |  +- com.github.jnr:jffi:jar:1.3.9:compile
[INFO] |  |  |  |  +- com.github.jnr:jffi:jar:native:1.3.9:runtime
[INFO] |  |  |  |  +- org.ow2.asm:asm-commons:jar:9.2:compile
[INFO] |  |  |  |  +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |  |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |  |  |  +- com.github.jnr:jnr-constants:jar:0.10.3:compile
[INFO] |  |  |  +- com.github.jnr:jnr-enxio:jar:0.32.13:compile
[INFO] |  |  |  \- com.github.jnr:jnr-posix:jar:3.1.15:compile
[INFO] |  |  +- org.ow2.asm:asm-util:jar:9.3:compile
[INFO] |  |  |  +- org.ow2.asm:asm:jar:9.3:compile
[INFO] |  |  |  +- org.ow2.asm:asm-tree:jar:9.3:compile
[INFO] |  |  |  \- org.ow2.asm:asm-analysis:jar:9.3:compile
[INFO] |  |  +- com.google.api-client:google-api-client:jar:1.34.0:compile
[INFO] |  |  |  +- com.google.oauth-client:google-oauth-client:jar:1.33.2:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-apache-v2:jar:1.41.7:compile
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[INFO] |  |  +- com.google.apis:google-api-services-sqladmin:jar:v1beta4-rev20220323-1.32.1:compile
[INFO] |  |  \- com.google.api:gax:jar:2.16.0:compile
[INFO] |  \- io.netty:netty-handler:jar:4.1.77.Final:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.77.Final:compile
[INFO] |     +- io.netty:netty-resolver:jar:4.1.77.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.77.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.77.Final:compile
[INFO] |     \- io.netty:netty-codec:jar:4.1.77.Final:compile
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:1.6.0:compile
[INFO] |  +- com.google.auto.value:auto-value-annotations:jar:1.9:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:1.6.0:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.41.7:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.31.0:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.31.0:compile
[INFO] |  +- com.google.http-client:google-http-client-gson:jar:1.41.7:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.9.0:compile
[INFO] |  \- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |     \- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] +- org.postgresql:postgresql:jar:42.3.5:runtime
[INFO] |  \- org.checkerframework:checker-qual:jar:3.5.0:compile
```

## Stacktrace
N/A

## How to reproduce

  1. Build a simple app with Spring Boot 2.7.0 and `com.google.cloud.sql:cloud-sql-connector-r2dbc-postgres` dependency to connect to a managed Postgres db in GCP

## Environment

1. OS type and version: [eclipse-temurin](https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin) , tested with both debian and centos flavors
2. Java SDK version: 17
2. Socket Factory version: 1.6.0

**Comment by kurtisvg** [comment] 2022-06-09 18:25
Hi @magiccrafter -- thanks for taking the time to look at this issue. @shubha-rajan has started looking into it, but we have a team event we're currently participating in so we probably won't have any update until next week.

In the meantime, it would be great if you can provide more details steps on reproducing this issue - a small sample app and instructions on how to identify the block is happening might be great.

**Comment by kurtisvg** [comment] 2022-06-29 17:05
Thanks for the work here, and sorry we haven't gotten a chance to look at this issue sooner -- we're stretch a little thin between holidays and summer vacations. 

This is a priority for us to try and address before the next release.

**Comment by kurtisvg** [comment] 2022-07-12 16:00
@magiccrafter I'm having some trouble replicating this -- in our own sample, it seems like my profiler is saying it's happening in a background thread.

I'm unable to run your example -- no matter what I configure it just says "password must not be null"

**Comment by kurtisvg** [comment] 2022-07-12 17:31
I've been playing around with this for couple of hours and managed to modify the app enough to get it to connect (I think?). 

But something is still going wrong -- if I call 'genN/100` I'm getting the following error:
```
Failed to obtain R2DBC Connection; nested exception is io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to IP/<unresolved>:3307
```
I don't really understand what this means -- our sample app seems to be working fine, so I don't think it's my configuration or set up. I am getting connections in my database, so it seems to be connecting okay. but I don't understand enough SpringBoot to know what's happening under the hood.

I'm going to bump this down to a p2 so it doesn't block the release -- not sure what's happening, but since we are unable to reproduce it I want to make it's a library problem and not an app problem.

**Comment by magiccrafter** [comment] 2022-07-12 19:09
I've switched to cloud sql auth proxy for gcp (as a sidecar) to use the latest Spring Boot version. Since then we don't observe any performance issues. imo the root cause is with the version mismatch of the `r2dbc-postgresql` library in your lib and the one coming with SB. I will keep an eye on the project and once you upgrade to `org.postgresql:r2dbc-postgresql:jar:0.9.1.RELEASE` I may give it another try.  Thanks.

**Comment by kurtisvg** [comment] 2022-07-12 19:11
@magiccrafter ah interesting - so you suspect it's a problem between `0.8.12.RELEASE` and `0.9.1.RELEASE`? I will take a look a second and see why we haven't updated

**Comment by kurtisvg** [comment] 2022-07-12 19:52
It looks like the problem was that the r2dbc driver moved group ids - I opened an issue on their repo (https://github.com/pgjdbc/r2dbc-postgresql/issues/530) and manually bump our version: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/909

**Comment by kurtisvg** [comment] 2022-07-13 18:25
@magiccrafter It seems like the version we released yesterday should have the newer r2dbc library. Can you check and see if you still have an issue or not?

**Comment by kurtisvg** [comment] 2022-07-22 21:57
Just wanted to follow up here. Did the new release solve the problem?

**Comment by magiccrafter** [comment] 2022-07-23 17:53
I will check it after my holiday. In two/three weeks time.

**Comment by kurtisvg** [comment] 2022-07-23 19:29
Thanks for the update! I'll close this out if I don't hear back in ~30 days or so

**Closed** 2022-08-19 22:28 UTC
Labels: type: question, priority: p2
